"""Evaluate a trained InterfaceCorrectionCNN checkpoint on the extrapolation
test cases generated by ml/generate_extrapolation_cases.py, reporting
per-field normalized RMSE, absolute (physical) MAE, and absolute A-B residual,
grouped by config ("config1"/"config2") and averaged across the 5 filter
widths within each config (same per-width-then-average methodology as
ml/test_model.py -- not sample-pooled, since widths aren't guaranteed to have
exactly equal case counts). A final average across both configs is also
reported.

Unlike ml/test_model.py's held-out set (unseen ICs within the training
distribution), these cases are sampled *outside* the training sweep's
[0.5x, 2x] pressure range on one side (see generate_extrapolation_cases.py),
so this measures extrapolation, not just interpolation to unseen ICs.

Usage:
    python3 -m ml.test_extrapolation --root plot_extrapolation --manifest runs_extrapolation/manifest.csv
"""

from __future__ import annotations

import argparse
import csv

import torch

from .dataset import list_cases
from .model import InterfaceCorrectionCNN
from .test_model import _build, _format_field_dict, evaluate
from .train import CHECKPOINT_PATH


def _load_extrapolation_manifest(path: str) -> dict[str, dict]:
    """-> {case_id: {"config": str, "spectral_filter_width": int}}"""
    out: dict[str, dict] = {}
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            out[row["case_id"]] = {
                "config": row["config"],
                "spectral_filter_width": int(row["spectral_filter_width"]),
            }
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", default=CHECKPOINT_PATH)
    ap.add_argument("--root", default="plot_extrapolation")
    ap.add_argument("--manifest", default="runs_extrapolation/manifest.csv")
    ap.add_argument("--batch-size", type=int, default=8)
    args = ap.parse_args()

    checkpoint = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    fields = checkpoint["fields"]
    grid_size = checkpoint["grid_size"]
    ring_width = checkpoint["ring_width"]
    field_stats = checkpoint["field_stats"]

    print(f"Loaded checkpoint from {args.checkpoint}")
    print(f"  fields={fields}  grid_size={grid_size}  ring_width={ring_width}")

    model = InterfaceCorrectionCNN(n_fields=len(fields))
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    manifest = _load_extrapolation_manifest(args.manifest)
    present = set(list_cases(args.root))
    manifest = {c: m for c, m in manifest.items() if c in present}
    if not manifest:
        raise SystemExit(f"No extrapolation cases from the manifest are present under {args.root}")

    by_config: dict[str, dict[int, list[str]]] = {}
    for case_id, m in manifest.items():
        by_config.setdefault(m["config"], {}).setdefault(m["spectral_filter_width"], []).append(case_id)

    config_avgs = {}
    for config_name in sorted(by_config):
        by_width = by_config[config_name]
        print(f"\n=== {config_name} ===")
        per_width = []  # [(loss, mae, norm_rmse, residual_mae), ...]
        for width in sorted(by_width):
            cases_w = sorted(by_width[width])
            try:
                ds = _build(args.root, cases_w, fields, grid_size, ring_width, field_stats)
            except FileNotFoundError as e:
                print(f"[filter width {width}] no readable samples ({len(cases_w)} cases): {e}")
                continue
            loss, mae, norm_rmse, residual_mae = evaluate(model, ds, fields, field_stats, args.batch_size)
            print(f"[filter width {width}] {len(ds)} samples over {len(cases_w)} cases  masked_mse={loss:.6f}")
            print(f"    normalized_rmse:   {_format_field_dict(norm_rmse)}")
            print(f"    absolute_mae:      {_format_field_dict(mae)}")
            print(f"    absolute_residual: {_format_field_dict(residual_mae)}")
            per_width.append((loss, mae, norm_rmse, residual_mae))

        n = len(per_width)
        avg_mae = {f: sum(m[f] for _, m, _, _ in per_width) / n for f in fields}
        avg_norm_rmse = {f: sum(nr[f] for _, _, nr, _ in per_width) / n for f in fields}
        avg_residual = {f: sum(r[f] for _, _, _, r in per_width) / n for f in fields}
        print(f"\n[{config_name} average across {n} width partitions]")
        print(f"    normalized_rmse:   {_format_field_dict(avg_norm_rmse)}")
        print(f"    absolute_mae:      {_format_field_dict(avg_mae)}")
        print(f"    absolute_residual: {_format_field_dict(avg_residual)}")
        config_avgs[config_name] = (avg_mae, avg_norm_rmse, avg_residual)

    names = sorted(config_avgs)
    overall_mae = {f: sum(config_avgs[c][0][f] for c in names) / len(names) for f in fields}
    overall_norm_rmse = {f: sum(config_avgs[c][1][f] for c in names) / len(names) for f in fields}
    overall_residual = {f: sum(config_avgs[c][2][f] for c in names) / len(names) for f in fields}
    print(f"\n=== average across {len(names)} configs ===")
    print(f"    normalized_rmse:   {_format_field_dict(overall_norm_rmse)}")
    print(f"    absolute_mae:      {_format_field_dict(overall_mae)}")
    print(f"    absolute_residual: {_format_field_dict(overall_residual)}")


if __name__ == "__main__":
    main()
